config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root  'mini_urls#new'

  post "/create_mini_url" => 'mini_urls#create'

  get "/show_mini_url/:id" => 'mini_urls#show'

  get "/stats" => 'mini_urls#index'

  post '/report_analytic' => 'mini_urls#report_analytic'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mini_url.rb
class MiniUrl < ApplicationRecord
	has_many :url_histories

	MINI_URL_LENGTH = 5

	before_create :generate_mini_url,:sanitize

	def generate_mini_url
		url = ([*('a'..'z'),*('0'..'9')]).sample(MINI_URL_LENGTH).join
		old_url = MiniUrl.where(short_url: url).last
		if old_url.present?
			self.generate_mini_url
		else
			self.short_url = url
		end
	end


	def sanitize
		self.original_url.strip!
		self.sanitize_url = self.original_url.downcase.gsub(/(https?:\/\/)|(www\.)/,"")
	  self.sanitize_url = "http://#{self.sanitize_url}"
	end
end

app/models/url_history.rb
class UrlHistory < ApplicationRecord
	serialize :countries,Array
	serialize :ip_addresses,Array

	belongs_to :mini_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mini_urls_controller.rb
class MiniUrlsController < ApplicationController

	def new
		@mini_url = MiniUrl.new
	end

	def create
	  #raise params.inspect
		@mini_url = MiniUrl.new(mini_url_params)
		if @mini_url.save
			@mini_urls = MiniUrl.all.order('created_at DESC')
			# redirect_to mini_urls_path
		else
			flash.now[:error]
			render 'new'
		end
  end

  def report_analytic
  	

  	#raise request.remote_ip.inspect
  	
  	#raise Geocoder.search('123.201.174.253').inspect
  	# raise request.location.inspect
  	# cnt = results.first.country
  	# raise cnt.inspect
  	remote_ip = request.remote_ip
  	results = Geocoder.search(remote_ip)
  	country = results.first.country
  	country = country || "India"
  	mini_url_rec = MiniUrl.find_by(id: params[:mini_url_id])
  	if mini_url_rec.present?
  		url_histories = mini_url_rec.url_histories
  		url_history_count = url_histories.count
  		if (url_history_count == 0)
  			click_count = 1
  		  ip_addresses = [remote_ip]
  		  countries = [country]
  			mini_url_rec.url_histories.create(click_count: click_count,countries: countries,ip_addresses: ip_addresses)
  		else
  			ip_addresses = mini_url_rec.url_histories.first.ip_addresses+[remote_ip]
  			click_count = mini_url_rec.url_histories.first.click_count+1
  			countries = mini_url_rec.url_histories.first.countries+[country]
  			mini_url_rec.url_histories.first.update(click_count: click_count,countries: countries.uniq!,ip_addresses: ip_addresses.uniq!)
  		end
  		redirect_to mini_url_rec.original_url
  	end
  end

  def index
  	@all_urls_list = MiniUrl.all.order('created_at DESC')
  end


  private
  def mini_url_params
  	params[:mini_url].permit(:original_url,:short_url,:sanitize_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mini_urls_helper.rb
module MiniUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortnerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mini_urls/_created_urls.html.erb
<% if @mini_urls.present? %> 
  <% @mini_urls.each do |mini_url| %> 
    <section class="panel"> 
      <div class="panel-body">
         
        <div class="fb-user-details">
         Here's your short URL!
          <p><b>OriginalUrl:</b> <%= mini_url.original_url %> </p>
          <p> <b> MiniUrl: </b> http://<%= mini_url.short_url %>.com </p>
        </div>
        <div class="clearfix"></div>
        
      </div>                            
    </section>
  <% end %>
<% end %>



 

app/views/mini_urls/_form.html.erb
<section class="panel panel-info">
  <header class="panel-heading">
    <h3>Welcome to short.com</h3> 
    <h2 class="col-lg-2 col-lg-offset-10">
    <%= link_to "Analytics", stats_path  %>
    </h2>
  </header>
  <div class="panel-body">
      <%= form_for @mini_url,url: create_mini_url_path, :html => { :class =>"form-horizontal row-fluid shift_from",remote: true} do |p| %>
      <form class="form-horizontal" role="form">
        <div class="form-group">
         Please enter your URL here
        </div>
        <div class="form-group">
          <div class="col-lg-8">
            <%= p.text_field :original_url, :class => "form-control ", :placeholder =>"type any url", :data => {:error => "Please Enter url"}, :required => true %>
            <!-- <span class="help-block with-errors"></span>   -->
            <button type="submit" class="btn btn-success">Submit 
            </button>            
          </div>
        </div>
        
     
      
      </form>
      
       <% end %>
  </div>
</section>

    








        

app/views/mini_urls/create.js.erb
$(".urls").html('<%= j render "mini_urls/created_urls", :@mini_urls => @mini_urls %>');

app/views/mini_urls/index.html.erb
<section class="panel panel-info">
<% if @all_urls_list.present? %> 
<header class="panel-heading">
<h3>Analytics</h3>
</header>


  <% @all_urls_list.each do |mini_url| %> 
    <section class="panel"> 
      <div class="panel-body">
         
        <div class="fb-user-details">
         Here's your short URL!
          <p><b>OriginalUrl:</b> <%= mini_url.original_url %> </p>
          <% short_url = mini_url.short_url %>
          <p> <b> MiniUrl: </b><%= link_to "https://short.com/#{short_url}.com", report_analytic_path(:mini_url_id => mini_url.id),
          :method => "post"  %> </p>
        </div>

        <div class="clearfix"></div>
        <div id="analytic_details">
          <div>
          <b>Total clicks: </b> <%= mini_url.url_histories.first.click_count rescue 0%>
          </div>
          <div>
          <b>Top countries: </b> <%= mini_url.url_histories.first.countries.join(',') rescue ""%>
          </div>
          <div>
          <b>IpAddresses: </b> <%= mini_url.url_histories.first.ip_addresses.join(',') rescue ""%>
          </div>
        </div>
      </div>                            
    </section>
  <% end %>
<% end %>

</section>

 

app/views/mini_urls/new.html.erb
<div>
<%= render "form",:@mini_url => @mini_url %>
</div>

<div class="urls">

</div>       